name: wheel_of_chores
description: Wheel of chores app
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.6'

dependencies:
  auto_route: ^7.8.1
  bloc: ^8.1.1
  dartx: ^1.2.0
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  pretty_dio_logger: ^1.3.1
  timeago: ^3.3.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.6.2
  mocktail: ^1.0.1
  r_resources: ^1.0.1
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/